### ISSUE TITLE
Fast scrolling does not match up with each other

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [stonko1994/SimultaneouslyScrollView#5]
Hi,

So I have two horizontal scrollViews. I want them to scroll simultaneously. It works as expected when I scroll in nominal speed, but if I scroll really fast it does not catch up to each other. Any idea how I can fix this?

```
var body: some View {
        return GeometryReader { geo in
            ZStack {
                // bars
                ScrollView(.horizontal, showsIndicators: false) {
                    LazyHStack(alignment: .bottom, spacing: spaceBetweenMarks) {
                        ForEach(0 ..< durationInSeconds, id: \.self) { i in
                            getBarsViewForIndex(i, geo: geo)
                        }
                    }
                }
                .introspectScrollView { simultaneouslyScrollViewHandler.register(scrollView: $0) }
                // numbers
                ScrollView(.horizontal, showsIndicators: false) {
                    LazyHStack(alignment: .top, spacing: spaceBetweenMarks) {
                        ForEach(0 ..< durationInSeconds, id: \.self) { i in
                            getNumbersViewForIndex(i, geo: geo)
                        }
                    }
                    .introspectScrollView { simultaneouslyScrollViewHandler.register(scrollView: $0) }
                }
            }
        }
    }
```

**Comment by stonko1994** [comment]
Hey,

I have never experienced that issue but I'll have a look at it.

Anyway I can see that you added the `.introspectScrollView` to the `LazyHStack` in your second `ScrollView`. That should go to the `ScrollView` as well. (But I doubt that this is causing the issue - I wonder why this even works)

**Comment by AnnieNinaJoyceV** [comment]
Hey!

I dropped this eventually. But if it may help, I shall get you a demo project of what I was trying.

**Comment by stonko1994** [comment]
Alright. If it doesn't block you any longer, I will close this issue for now.

If anyone has the same issue, feel free to reopen it.
