### ISSUE TITLE
Problem when you change direction of the scroll in one view while both views moving

### ISSUE THREAD

**Issue by yarbsea** [stonko1994/SimultaneouslyScrollView#7]
Setup scroll view 1 and 2 side by side and setup code.

scroll views are large array of numbers for example 1...1000

Drag scroll view 1 in one direction, and both lists will scroll simultaneously correctly.

Now let off the gesture on list 1, and the inertia of the scroll will continue moving the two lists, but now touch the list 2 and drag it the opposite direction. Now the two lists will NOT be synchronized any longer, and when they run out of inertia they will be messed up. Only fix now is to let off the screen, then touch to drag and they re-synch.

?

https://user-images.githubusercontent.com/132616008/236322237-652ad3fb-6fee-4520-82d3-eb27581ffd59.mov

**Comment by stonko1994** [comment]
Thanks for reporting. I will see if there is an easy fix to this.

**Comment by yarbsea** [comment]
Awesome! thanks

**Comment by stonko1994** [comment]
This was fixed and released in `1.0.1` 🥳
